### ISSUE TITLE
JWE decryption has trailing characters Description

### ISSUE THREAD

**Issue by aenand** [Mastercard/client-encryption-ruby#9]
#### Bug Report Checklist

- [ ] Have you provided a code sample to reproduce the issue?
- [ ] Have you tested with the latest release to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?

**Description**
The JWE decryption service with AES 128Bit-CBC and RSA-OAEP-256 fails to properly decrypt the data. It results in having trailing characters that causes the JSON parser to return a string not a hash and causes issues downstream when attempting to consume the data. 

**To Reproduce**
Call decrypt with AES 128Bit-CBC and RSA-OAEP-256

**Expected behavior**
The decryption service should return a valid hash with no trailing characters. 

**Additional context**
We are trying to use this as part of the Click to Pay process.

**Suggest a fix/enhancement**
I have a PR up to remove `padding=0` which seems to solve the problem though I am not an expert in this field by any means.

**Comment by danny-gallagher** [comment]
Hi @aenand, Thanks for raising the issue and also creating the PR.
We've merged your PR into the main branch and will be releasing a new version of the library shortly.

EDIT: The new version is now available: https://rubygems.org/gems/mastercard-client-encryption/versions/1.3.1
